### ISSUE TITLE
Limited results

### ISSUE THREAD

**Issue by xilopaint** [godbout/alfred-kat#2]
If I query the workflow for `def` it won't return a result whose torrent name is `abc.def.ghi`. It's a different behaviour from the original KAT workflow.

**Comment by godbout** [comment]
It's because v2 is using the main kat site while the previous versions were using a non-official mirror (that went down for two days some days ago). Unfortunately I'm just displaying what is sent back by the site, and yes, good point, it doesn't return the torrents that include dots. I'll check other mirrors and see. For the time being if you prefer the old versions, you can still downloaded it here: https://github.com/godbout/alfred-kat/releases

**Comment by xilopaint** [comment]
For the time being, I'm sticking with v2 which has a great performance. Thank you for your work.

**Comment by godbout** [comment]
I've checked all the list of official mirrors and they all don't return torrent names with dots. Only some unofficial do. But those torrents still appears normally with spaces on the official ones. Have a look below:

![Download_fight_club_Torrents_-_Kickass_Torrents_and_godbout_alfred-kat__KAT_workflow_for_Alfred__search_and_open_magnet_links_directly_from_Alfred_and_Why_do_torrents_often_have_periods_in_their_name____Piracy](https://user-images.githubusercontent.com/121373/55290168-35281d80-5402-11e9-8617-2e0249816ca6.png)

So it seems you should be able to find what you're looking for!

**Comment by xilopaint** [comment]
It sounds good to me, thanks!
